### ISSUE TITLE
Create branch in GeoConcerns for turning into a Hydra Plugin

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hydra_plugins_wg#13]
**Done when** branch is created.

**Comment by afred** [comment]
@eliotjordan once created, just put a link to the branch in here, and feel free to close it yourself.

Do you think we have enough to get started on creating some initial tickets?

**Comment by eliotjordan** [comment]
Branch for plugins work: https://github.com/projecthydra-labs/geo_concerns/tree/plugin

@afred I do think we have enough material for some tickets. I'll get some in the hopper tomorrow.
