### ISSUE TITLE
User Stories Vocabulary

### ISSUE THREAD

**Issue by carolyncole** [projecthydra-labs/hydra_plugins_wg#2]
* **A plugin** is software that can be optionally installed into CurationConcerns.
* **The documentation** is the sum of documents, tutorials, etc. that explain the guidelines for  developing plugins.
* **A developer** is one who is writing code for plugin.
* **An implementer** is one who installs and/or manages the installation of a product within the Hydra stack for production use.

**Comment by botimer** [comment]
Some question about the exact scope of "what is plugged into". It may not ultimately be CurationConcerns, but that seems the likely destination "for now", possibly to be extracted to a more general Hydra layer.

**Comment by drh-stanford** [comment]
Aren't there two primary classes of developers? The "plugin developer" who is developing the plugin coding to an API, and an "API developer" who is developing the API itself and its surfacing in Hydra (CurationConcerns/Haiku). It seems that both cases are relevant to our use cases.

**Comment by mbarnett** [comment]
+1 Yeah, I would strongly expect we're going to have to recommend additional "plugin surface area" to Hydra/Curation Concerns/Haiku where it doesn't currently exist.

**Comment by afred** [comment]
@mbarnett @drh-stanford Please check out the PR and merge if it looks good. Thanks!
