### ISSUE TITLE
Will plugins be more specific than a Rails Engine or Railtie?

### ISSUE THREAD

**Issue by grosscol** [projecthydra-labs/hydra_plugins_wg#22]
> Plugins should be Railties or Rails engines unless there is good reason to do otherwise.

I concur here, but am I correct in assuming that there will be a specific subclass of Railtie or Engine that a plugin needs to be and implement some methods.  Like a contract or interface.  My concern is that engine and railtie are pretty broad.

**Comment by afred** [comment]
@grosscol we don't know what the interface looks like yet, so can't say for sure. But subclassing `Railtie` or `Engine` would probably make sense.

**Comment by afred** [comment]
Official answer to this is: possibly, but only as needed. For now, we'll instruct plugin developers to use interfaces provided by `Rails::Engine` and `Rails::Railtie` as much as we can. Any opinionated pattens to which we want all plugins to adhere should be first articulated in the Guidelines. After that, if it seems reasonable to codify one or more guidelines to make it more straightforward for plugin developers, then we can consider doing so under a `Hyrax::Plugins` namespace, either through plain-old inheritance, or some other mechanism.

Closing this ticket, but feel free to re-open (or create a new one) if this topic needs more discussion.
