### ISSUE TITLE
Plugins should only generate code into the host app when necessary

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hydra_plugins_wg#29]
**Rationale:** generated code leads to maintenance issue when upgrading plugin versions, or versions of Hyrax. Keeping plugin code in the plugin's gem location is a more maintainable solution, so if a file does  not have to be copied into the host app, then don't.

**Done when** guideline is accepted, or rejected.

**Comment by afred** [comment]
@projecthydra-labs/hydra_file_sets_wg thoughts?

**Comment by afred** [comment]
@projecthydra-labs/hydra_plugins_wg specifically, how should this guideline be worded? I think "when necessary" is a little too vague. Or maybe this is ok, but should be elaborated on with a **justification**.

**Comment by mbarnett** [comment]
To some extent this amounts to "use good judgement and taste" which is a hard thing to codify precisely.

Would it help to enumerate (non-exhaustively) some reasons where it might be necessary, and some common examples of where we see it happening that maybe aren't necessary?

**Comment by afred** [comment]
@mbarnett I'm wondering if there is a way to word it to be more specific than simply  "use good judgement".

Thinking about it a bit more, and after talking with @eliotjordan, I think the tendency to copy config into the host app stems from the expectation that the user will want to alter the config in some way.

This is fine, however, a lot of times the situation is this: the implementer is required to change about 2% of the configuration (i.e. specifying API keys, or session secrets, etc) while the remaining 98% of config will work with default values.

What I see a lot of gems and engines do (including Rails, Devise, RSpec, etc) is that they will generate a mostly passive config file into your host app, and direct you (with code comments and documentation) which config options the user _needs_ to change, while providing all the other config options that the implementer _may_ change. And if the implementer chooses not to change those optional settings, then they default to values specified within the gem's code.

I don't mind this approach. It doesn't completely eliminate the problem with upgrades, but it's much cleaner than have a single location for plugin config, which is copied to the host app after running the install generator, which is the situation we found in GeoConcerns, and the primary one I think our guidelines should try to prevent.
