### ISSUE TITLE
The software expectations of plugins are well-documented for the developer.

### ISSUE THREAD

**Issue by carolyncole** [projecthydra-labs/hydra_plugins_wg#3]
Depends on #2 

As a developer, 
who is reading the documentation for developing plugins,
I know the expectations that the Hydra software will have of my plugin 
so that I do not develop a plugin that will break a Hydra instance
by violating those expectations.

**Comment by starsplatter** [comment]
"so I can develop a plugin that will conform to expectations."

**Comment by drh-stanford** [comment]
It seems that semantic versioning adherence is applicable here -- as the expections will change across versions.

**Comment by afred** [comment]
@drh-stanford do you think we need to say something explicitly here about semver, or are you just suggesting that the Guidelines should follow semver?
