### ISSUE TITLE
How to monkey patch

### ISSUE THREAD

**Issue by afred** [projecthydra-labs/hydra_plugins_wg#30]
**done when:** guideline is added (or rejected) that describes an acceptable pattern for monkey patching, specifically using `alias_method_chain`

**Comment by jeremyf** [comment]
*sniffle*

**Comment by jcoyne** [comment]
`alias_method_chain` is deprecated in rails 5. It's not a good pattern.

**Comment by afred** [comment]
OK, thanks!

**Comment by afred** [comment]
@jcoyne @jeremyf So... we're wondering which of the following is better?...
  1. Guidelines that try to prevent gross monkey patching.
  1. Guidelines that say "don't monkey patch"
  1. Nothing

thoughts?

**Comment by jcoyne** [comment]
Don't monkey patch.  If you think you need to, then you ought to refactor the host application to provide a configuration point.
