### ISSUE TITLE
Installing and configuring a plugin is predictable and straightforward.

### ISSUE THREAD

**Issue by carolyncole** [projecthydra-labs/hydra_plugins_wg#6]
Depends on #2 

As an implementer of CurationConcerns,
I can expect that the installation and configuration of a plugins will be similar to other plugins
so that installing new plugins is a predictable process with minimal overhead.

**Comment by botimer** [comment]
We may add some acceptance criteria regarding a suggested documentation format/template, which the first few plugins follow to set precedent.

**Comment by afred** [comment]
@botimer good idea. I added it to [the agenda for next meeting](https://wiki.duraspace.org/display/hydra/2016-12-06+Meeting+notes+-+Hydra+Plugins+Working+Group).

Note that [Hydra's contributing guidelines](https://github.com/projecthydra/hydra/blob/master/CONTRIBUTING.md#documenting-code) say something about what to document, and to use Yard when doing so. And while several Hydra products do this minimally, there certainly does not seem to be much enforcement to make sure people are following through.
