### ISSUE TITLE
Should GeoConcerns be one of our proofs-of-concept projects?

### ISSUE THREAD

**Issue by eliotjordan** [projecthydra-labs/hydra_plugins_wg#7]
* Add a 👍 to _this_ comment if you want this to be one of our deliverables.
* Use comments below this one to discuss pros and cons of each candidate.
* On 2016-12-06 (Meeting 3), we'll review the candidates with the most 👍's, and choose at least 2 projects to get started on.

**Comment by drh-stanford** [comment]
Documentation and tutorials are available here -- http://geoconcerns.github.io
Codebase is here -- https://github.com/projecthydra-labs/geo_concerns

**Comment by eliotjordan** [comment]
Pros: Existing code base that will be in production soon (Princeton).
Cons: Rather complex with some amount of domain specific (GIS) knowledge needed.

**Comment by afred** [comment]
@eliotjordan to what degree is the domain specific knowledge involved with the interfaces between the plugin (GeoConcerns) and it's host (CurationConcerns)?

**Comment by eliotjordan** [comment]
@afred I think it's manageable, but I just wanted to point out that there is some extra overhead in terms of complexity.

**Comment by eliotjordan** [comment]
I'm currently working on integrating our existing hydra head (plum) with GeoConcerns. Derivative creation is a major pain point that I hope we can tackle.

https://github.com/pulibrary/plum/issues/843

**Comment by afred** [comment]
CHOSEN!
