### ISSUE TITLE
Should Google Analytics be be one of our proofs-of-concept projects?

### ISSUE THREAD

**Issue by carolyncole** [projecthydra-labs/hydra_plugins_wg#8]
* Add a 👍 to _this_ comment if you want this to be one of our deliverables.
* Use comments below this one to discuss pros and cons of each candidate.
* On 2016-12-06 (Meeting 3), we'll review the candidates with the most 👍's, and choose at least 2 projects to get started on.

**Comment by afred** [comment]
CHOSEN!
